#pragma once

#include <SDL3/SDL.h>
#include <stdint.h>

typedef enum TetrominoColor : uint32_t {
  TETROMINO_CYAN = 0x00F0F0FF,
  TETROMINO_BLUE = 0x0000F0FF,
  TETROMINO_ORANGE = 0xF0A000FF,
  TETROMINO_YELLOW = 0xF0F000FF,
  TETROMINO_GREEN = 0x00F000FF,
  TETROMINO_PURPLE = 0xA000F0FF,
  TETROMINO_RED = 0xF00000FF,
} TetrominoColor;

static const TetrominoColor COLORS[] = {
  TETROMINO_PURPLE,
  TETROMINO_RED,
  TETROMINO_GREEN,
  TETROMINO_ORANGE,
  TETROMINO_BLUE,
  TETROMINO_YELLOW,
  TETROMINO_CYAN,
};

typedef enum SquareColor : uint32_t {
  SQUARE_DEFAULT = 0xCC8081FF,
  SQUARE_BORDER_TOP = 0xFFFFFF99,
  SQUARE_BORDER_BOTTOM = 0x00000080,
  SQUARE_BORDER_SIDE = 0x0000001A,
} SquareColor;

typedef enum UiColor : uint32_t {
  UI_BACKGROUND = 0x333333FF,
  UI_SIDEBAR_BACKGROUND = 0x545454FF,
  UI_POPUP_BACKGROUND = 0x212121FF,
  UI_BUTTON_BACKGROUND = TETROMINO_CYAN,
  UI_GUIDE = 0x555555FF,
  UI_WHITE_TEXT = 0xFFFFFFFF,
  UI_POPUP_TEXT = 0xEFEFEFFF,
  UI_BUTTON_TEXT = 0x212121FF,
} UiColor;

void App_SetRenderDrawColor(SDL_Renderer *, uint32_t);
SDL_Color App_Color(uint32_t);
SDL_FColor App_FColor(uint32_t);
